import { IEvent, TColumns } from "./model/table";
import { v4 as uuidv4 } from "uuid";
export const tableHead = [
  { id: uuidv4(), type: "audience", title: "Аудитория" },
  { id: uuidv4(), type: "time", title: "8:00" },
  { id: uuidv4(), type: "time", title: "9:00" },
  { id: uuidv4(), type: "time", title: "10:00" },
  { id: uuidv4(), type: "time", title: "11:00" },
  { id: uuidv4(), type: "time", title: "12:00" },
  { id: uuidv4(), type: "time", title: "13:00" },
  { id: uuidv4(), type: "time", title: "14:00" },
  { id: uuidv4(), type: "time", title: "15:00" },
  { id: uuidv4(), type: "time", title: "16:00" },
  { id: uuidv4(), type: "time", title: "17:00" },
  { id: uuidv4(), type: "time", title: "18:00" },
];
export const eventDataMock: IEvent = {
  id: uuidv4(),
  type: "event",
  time: ["8:00", "9:30"],
  name: "Уорхол",
  description: "Уорхол",
};
export const eventDataMock_2: IEvent = {
  id: uuidv4(),
  type: "event",
  time: ["10:00", "12:00"],
  name: "IT news",
  description: "online конференция",
};
export const columnsFromBackend: TColumns = {
  [uuidv4()]: {
    nameData: { id: uuidv4(), type: "audience", title: "Уорхол", count: "20 мест" },
    columnsTime: [
      { columnId: uuidv4(), event: eventDataMock },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
    ],
  },
  [uuidv4()]: {
    nameData: { id: uuidv4(), type: "audience", title: "Да винчи", count: "15 мест" },
    columnsTime: [
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: eventDataMock_2 },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
      { columnId: uuidv4(), event: { id: uuidv4() } },
    ],
  },
};
